import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.scss";
import "bootstrap-icons/font/bootstrap-icons.css";
import ConditionalLayout from "@/app/components/ConditionalLayout";
import RefTagger from "@/app/components/RefTagger";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConditionalLayout>{children}</ConditionalLayout>
        <RefTagger />
      </body>
    </html>
  );
}
